### ISSUE TITLE
get function has wrong variable for height

### ISSUE THREAD

**Issue by njake** [Gregwar/GnuPlot#9]
$this->sendCommand("set terminal $format size {$this->width}{$this->unit}, {$this->width}{$this->unit}");
Should be
$this->sendCommand("set terminal $format size {$this->width}{$this->unit}, {$this->height}{$this->unit}");

**Comment by bobemoe** [comment]
Just ran across this bug too. It means it's impossible to set the height of a graph that is fetched with `get()`.  This same code in `write()` is actually correct.

I will create PR
